name: formal
# either manually started, or on a schedule
on: [ push, workflow_dispatch, pull_request ]

jobs:
  gds:
    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out

    - name: checkout repo
      uses: actions/checkout@v3

    # Set Python up
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python requirements
      run: pip3 install -r py/requirements.txt

    - name: Make tt_defs.vh
      run: make rtl/tt_defs.vh

    - name: checkout openlane2 repo
      uses: actions/checkout@v3
      with:
        repository: efabless/openlane2
        path: openlane2

    - uses: cachix/install-nix-action@v20

    - name: Harden tt_ctrl
      working-directory: ol2/tt_ctrl
      run: nix-shell openlane2/shell.nix --run "python build.py"      

    - name: Harden tt_mux
      working-directory: ol2/tt_mux
      run: nix-shell openlane2/shell.nix --run "python build.py"      

    # install oss fpga tools for cocotb and iverilog
#    - name: install oss-cad-suite
#      uses: YosysHQ/setup-oss-cad-suite@v2
#      with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#    - run: | 
#        yosys --version
    