name: formal
# either manually started, or on a schedule
on: [ push, workflow_dispatch, pull_request ]

jobs:
  gds:
    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out

    - name: checkout repo
      uses: actions/checkout@v3

    - name: checkout openlane2 repo
      uses: actions/checkout@v3
      with:
        repository: efabless/openlane2
        path: openlane2

    - uses: cachix/install-nix-action@v20

    - name: Harden with openlane 2
      run: nix-shell openlane2/shell.nix --run "openlane -p sky130A ol2/top/config.json"

    # install oss fpga tools for cocotb and iverilog
#    - name: install oss-cad-suite
#      uses: YosysHQ/setup-oss-cad-suite@v2
#      with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#    - run: | 
#        yosys --version
    
    - name: python requirements
      run: pip3 install -r py/requirements.txt

    # formal
    - name: formal tristate
      run: |
        make formal_tristate 

    - name: formal tristate
      run: |
        make formal_connectivity
