name: gds
# either manually started, or on a schedule
on: [ push, workflow_dispatch, pull_request ]

jobs:
  gds:
    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out

    - name: checkout repo
      uses: actions/checkout@v3

    # Set Python up
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python requirements
      run: pip3 install -r py/requirements.txt

    - name: Make tt_defs.vh
      run: make rtl/tt_defs.vh

    - name: checkout openlane2 repo
      uses: actions/checkout@v3
      with:
        repository: efabless/openlane2
        path: openlane2

    - uses: cachix/install-nix-action@v20
      
    - uses: cachix/cachix-action@v12
      with:
        name: openlane
        extraPullNames: openlane

    - name: Install Sky130 PDK
      run: |
        pip3 install volare
        volare enable --pdk sky130 af3485525297d5cbe93c129ea853da2d588fac41

    - name: Harden tt_ctrl
      working-directory: ol2/tt_ctrl
      run: nix-shell $GITHUB_WORKSPACE/openlane2/shell.nix --run "python build.py"      

    - name: Harden tt_mux
      working-directory: ol2/tt_mux
      run: nix-shell $GITHUB_WORKSPACE/openlane2/shell.nix --run "python build.py"

    - name: Prepare configuration
      run:
        echo TODO

    - name: Copy final results
      run: |
        mkdir -p gds spef lef verilog/gl
        cp ol2/tt_ctrl/runs/RUN_*/final/gds/tt_ctrl.magic.gds gds/tt_ctrl.gds
        cp ol2/tt_ctrl/runs/RUN_*/final/lef/tt_ctrl.lef lef/tt_ctrl.lef
        cp ol2/tt_ctrl/runs/RUN_*/final/pnl/tt_ctrl.pnl.v verilog/gl/tt_ctrl.v
        cp ol2/tt_ctrl/runs/RUN_*/final/nl/tt_ctrl.nl.v verilog/gl/tt_ctrl.nl.v
        cp -r ol2/tt_ctrl/runs/RUN_*/final/spef/* spef/
        cp ol2/tt_mux/runs/RUN_*/final/gds/tt_mux.magic.gds gds/tt_mux.gds
        cp ol2/tt_mux/runs/RUN_*/final/lef/tt_mux.lef lef/tt_mux.lef
        cp ol2/tt_mux/runs/RUN_*/final/pnl/tt_mux.pnl.v verilog/gl/tt_mux.v
        cp ol2/tt_mux/runs/RUN_*/final/nl/tt_mux.nl.v verilog/gl/tt_mux.nl.v
        cp -r ol2/tt_mux/runs/RUN_*/final/spef/* spef/

    - name: upload macros artifact
      uses: actions/upload-artifact@v3
      with:
          name: macros
          path: |
            gds/*
            lef/*
            spef/*
            verilog/gl/*
